# Generated by Django 3.2.5 on 2021-07-06 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('ocupado', models.BooleanField(default=False)),
                ('detalle', models.CharField(max_length=400)),
                ('precio', models.FloatField()),
                ('dormitorios', models.IntegerField()),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField(max_length=14)),
                ('cp', models.CharField(blank=True, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PAGADO', 'PAGADO'), ('ELIMINADO', 'ELIMINADO')], default=('PENDIENTE', 'PENDIENTE'), max_length=45)),
                ('metodo_pago', models.CharField(blank=True, choices=[('EFECTIVO', 'EFECTIVO'), ('TRANSFERENCIA', 'TRANSFERENCIA'), ('CHEQUE', 'CHEQUE'), ('TARJETA', 'TARJETA'), ('CRIPTODIVISA', 'CRIPTODIVISA')], max_length=45)),
                ('monto_pagado', models.FloatField(default=0)),
                ('dias_reserva', models.PositiveIntegerField(default=1)),
                ('fk_cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.user')),
                ('fk_habitacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_app.room')),
            ],
        ),
    ]
