# Generated by Django 3.2.5 on 2021-07-06 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cp',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='direccion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('PAGADO', 'PAGADO'), ('ELIMINADO', 'ELIMINADO')], default=('PENDIENTE', 'PENDIENTE'), max_length=45)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'EFECTIVO'), ('TRANSFERENCIA', 'TRANSFERENCIA'), ('CHEQUE', 'CHEQUE'), ('TARJETA', 'TARJETA'), ('CRIPTODIVISA', 'CRIPTODIVISA')], max_length=45)),
                ('monto_pagado', models.FloatField(default=0)),
                ('dias_reserva', models.PositiveIntegerField(default=1)),
                ('fk_cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hotel_app.user')),
                ('fk_habitacion', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_app.room')),
            ],
        ),
    ]
