# Generated by Django 3.2.5 on 2021-07-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0004_alter_user_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('EFECTIVO', 'EFECTIVO'), ('TRANSFERENCIA', 'TRANSFERENCIA'), ('CHEQUE', 'CHEQUE'), ('TARJETA', 'TARJETA'), ('CRIPTODIVISA', 'CRIPTODIVISA')], max_length=45),
        ),
    ]
