# Generated by Django 3.2.5 on 2021-07-06 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0007_alter_booking_fk_habitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='fk_cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.user'),
        ),
    ]
