# Generated by Django 3.2.5 on 2021-07-06 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_app', '0008_alter_booking_fk_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='fk_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel_app.user'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='fk_habitacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='hotel_app.room'),
        ),
    ]
